version: "3.8"

services:
  frontend:
    image: kamalsharma93/vidly-fe:1
    depends_on: 
      - backend
    ports:
      - 3000:3000

  backend:
    image: kamalsharma93/vidly-be:1
    depends_on: 
      - db
    ports: 
      - 3001:3001
    environment: 
      DB_URL: mongodb://db/vidly
    command: ./docker-entrypoint.sh

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db

volumes:
  vidly:
